-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 00:51:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema studentStatus
-- -----------------------------------------------------
-- 学籍管理系统的数据库
DROP SCHEMA IF EXISTS `studentStatus` ;

-- -----------------------------------------------------
-- Schema studentStatus
--
-- 学籍管理系统的数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `studentStatus` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `studentStatus` ;

-- -----------------------------------------------------
-- Table `studentStatus`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentStatus`.`permission` (
  `id` TINYINT NOT NULL COMMENT '1-超管；2-普管；3-老师；4-学生',
  `describe` VARCHAR(45) NOT NULL COMMENT '描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studentStatus`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentStatus`.`userType` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `describe` VARCHAR(45) NOT NULL COMMENT '类型描述',
  `permission_id` TINYINT NOT NULL COMMENT '类型所属权限的ID',
  PRIMARY KEY (`id`),
  INDEX `type_perrmission_id_fk_idx` (`permission_id` ASC),
  CONSTRAINT `type_perrmission_id_fk`
    FOREIGN KEY (`permission_id`)
    REFERENCES `studentStatus`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studentStatus`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentStatus`.`user` (
  `id` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(45) NULL COMMENT '用户姓名',
  `typeId` TINYINT NOT NULL COMMENT '用户类型ID',
  `college` VARCHAR(45) NULL COMMENT '用户所属学院',
  `sex` TINYINT NULL COMMENT '性别',
  `age` TINYINT NULL COMMENT '年龄',
  `major` VARCHAR(45) NULL COMMENT '专业',
  `class` VARCHAR(45) NULL COMMENT '班级',
  `birthday` DATE NULL COMMENT '生日',
  PRIMARY KEY (`id`),
  INDEX `user_type_id_fk_idx` (`typeId` ASC),
  CONSTRAINT `user_type_id_fk`
    FOREIGN KEY (`typeId`)
    REFERENCES `studentStatus`.`userType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studentStatus`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentStatus`.`grade` (
  `id` TINYINT NOT NULL DEFAULT 1,
  `userId` TINYINT NOT NULL COMMENT '用户ID',
  `chinese` DOUBLE NULL COMMENT '语文成绩',
  `english` DOUBLE NULL COMMENT '英语成绩',
  `math` DOUBLE NULL COMMENT '数学成绩',
  `physics` DOUBLE NULL COMMENT '物理成绩',
  `chemistry` DOUBLE NULL COMMENT '化学成绩',
  `biology` DOUBLE NULL COMMENT '生物成绩',
  PRIMARY KEY (`id`),
  INDEX `grade_user_id_fk_idx` (`userId` ASC),
  CONSTRAINT `grade_user_id_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `studentStatus`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
